apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernets-app-deployment
  labels:
    app: kubernetes-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubernetes-app
  template:
    metadata:
      labels:
        app: kubernetes-app
    spec:
      containers:
      - name: kubernetes-app
        image: hecha00/kubernetes-app:3.0
        ports:
        - containerPort: 3000
        readinessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 5
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "400m"
            memory: "126Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-app
  annotations:
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: kubernetes-app
  type: LoadBalancer
