apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-app
  labels:
    app: fist-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: first-app
  template:
    metadata:
      labels:
        app: first-app
    spec:
      containers:
      - name:  golang-app
        image: hecha00/golang-app:latest
        ports:
        - containerPort: 8080