apiVersion: v1
kind: Namespace
metadata:
  name: go-namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-deployment
  name: go-namespace
  labels:
    app: go-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
      - name: go-app
        image: hecha00/go-webserver:1.0
        ports:
        - containerPort: 4000
      nodeSelector:
        cputype: ubuntu
---
apiVersion: v1
kind: Service
metadata:
  name: my-go-service
  namespace: go-namespace
spec:
  type: NodePort
  selector:
    app: go-app
  ports:
  - protocol: TCP
    port: 4000
    targetPort: 4000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: test.it
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: my-go-service
                port:
                  number: 4000