---
apiVersion: v1
kind: Secret
metadata:
  name: permission-manager
  namespace: permission-manager
type: Opaque
stringData:
  PORT: "4000" # port where server is exposed
  CLUSTER_NAME: "kubespray-version" # name of the cluster to use in the generated kubeconfig file
  CONTROL_PLANE_ADDRESS: "https://192.168.0.158" # full address of the control plane to use in the generated kubeconfig file
  BASIC_AUTH_PASSWORD: "ciao" # password used by basic auth (username is `admin`)
